# Generated by Django 4.2.11 on 2024-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Travel_Blog', max_length=255),
        ),
    ]
